import "./globals.css"
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Leaderboard',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-[#111827]"/*style={{ backgroundColor:"#111827"}}*/>
      <div style={{display:"flex", justifyContent:"center", backgroundColor:"#06b6d4"}}>
      <h1 className="h-20 font-extrabold text-4xl mt-7">Sudoku Leaderboard</h1>
      </div>
      {children}
      </body>
    </html>
  )
}
